apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webpage
  labels:
    app: simple-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webpage
  template:
    metadata:
      labels:
        app: simple-webpage
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

