apiVersion: v1
kind: Service
metadata:
  name: simple-webpage-service
spec:
  type: NodePort # For simplicity, using NodePort to expose the service
  selector:
    app: simple-webpage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30007 # Optional: specify a node port; otherwise, Kubernetes will allocate one

